@startuml
'https://plantuml.com/class-diagram

class ToDoListManager{
    main()
    start()
}

class ToDoListController{

    - addButton: Button
    - clearListButton: Button
    - updateTaskButton: Button
    - removeTaskButton: Button
    - clearFieldsButton: Button

    - menuBar: MenuBar
    - viewComboBox: ComboBox<String>
    - errorLabel: Label

    - tableView: TableView<Task>
    - taskDescriptionColumn: TableColumn<Item, String>
    - dueDateColumn: TableColumn<Item, LocalDate>
    - statusColumn: TableColumn<Item, String>

    - descriptionTextField: TextField
    - dueDatePicker: DatePicker

    - observableTaskList: ObservableList<Task>

    + initialize()
    + filter()

    + menuItemOpenListClicked()
        + loadFile() /'loadFile() also calls clearObservableList()'/

    + menuItemSaveListClicked()
        + saveFile()

    + menuItemGetHelpClicked()

    + clearListButtonClicked()
        + clearObservableList()

    + addButtonClicked()     /'Delegate testing'/
    + removeButtonClicked()  /'Delegate testing'/
    + onEditTaskStatus()
    + updateView()
    + updateTaskButtonClicked() /'Delegate testing'/
        + void updateTaskTest()
    + clearFieldsButtonClicked()
        + clearFields()
    + closeApp()
}

class Task{
    - taskDescription : SimpleStringProperty
    - dueDate: LocalDate
    - status: SimpleStringProperty

    + setItemDescription()
    + getItemDescription()
    + setStatus()
    + getStatus()
    + setDueDate()
    + getDueDate()
    + convertToString()
}

javafx.Application <|-- ToDoListManager
ToDoListManager - ToDoListController
ToDoListController - Task


@enduml